### ISSUE TITLE
Qemu fails to set up vhost-user memory map

### ISSUE THREAD

**Issue by glitzflitz** [stefano-garzarella/vhost-user-vsock#7]
Not sure if this is vhost-user-vsock problem but seems like qemu is not able to use hugepages
```
qemu-system-x86_64: Failed initializing vhost-user memory map, consider using -object memory-backend-file share=on
qemu-system-x86_64: vhost_set_mem_table failed: Resource temporarily unavailable (11)
qemu-system-x86_64: Error starting vhost: 11
```

**Comment by stefano-garzarella** [comment]
Please post the QEMU string you're using and the QEMU version.

**Comment by glitzflitz** [comment]
```
qemu-system-x86_64 -cpu host -M q35,accel=kvm -smp 2 -m 1G \
    -object memory-backend-file,id=mem,size="1G",mem-path="/dev/hugepages",share=on \
    -drive file=$FILE,format=raw,id=hd0,if=none \
    -device virtio-blk-pci,drive=hd0 \
    -chardev socket,id=char0,reconnect=0,path=/tmp/vhost4.socket \
    -device vhost-user-vsock-pci,chardev=char0
```
For some reason with if=none guest can't find uuid of the drive and drops me in rootfs shell.
I have to use fallback initramfs to boot. I'm using qemu 5.2.0

**Comment by stefano-garzarella** [comment]
You should check if `hugepages` are allocated.

If `cat /proc/sys/vm/nr_hugepages` returns 0 you should allocate some of them (depending on your total amount of memory).
`sysctl -w vm.nr_hugepages=512` will reserve 1GB of hugepages (2MB of each page).
`echo "vm.nr_hugepages=512" >> /etc/sysctl.conf` to make it persistent.

> 
> For some reason with if=none guest can't find uuid of the drive and drops me in rootfs shell.
> I have to use fallback initramfs to boot. I'm using qemu 5.2.0

I think this issue is not related. I usally use virt-builder to create the image VM.

**Comment by glitzflitz** [comment]
I allocated 3GB of hugepages with boot parameters.
```
  "root=/dev/nvme0n1p4 rw add_efi_memmap  hugepagesz=1G hugepages=3 default_hugepagesz=1G intel_iommu=on iommu=pt"
```

**Comment by stefano-garzarella** [comment]
Did you check if they are allocated through `cat /proc/sys/vm/nr_hugepages`?

**Comment by glitzflitz** [comment]
Yes. 
```
~ ❯❯❯ cat /proc/sys/vm/nr_hugepages
3
```

**Comment by stefano-garzarella** [comment]
Strange, maybe there is some issue with permission.
Did you try with `sudo`?

Otherwise you can try to remove the boot parameters and try with the sysctl at runtime.

**Comment by glitzflitz** [comment]
Ah you are right. I was running the command from the script without `sudo` inside it. The strange thing is guest still drops me 
in rootfs shell because it can't find uuid but it is able to run normally with fallback initramfs
